--CREATE DATABASE CDI;


USE CDI;

DROP TABLE EMP;
DROP TABLE DEPT;  
DROP TABLE PROJET;
GO
	
CREATE TABLE DEPT(
	DEPTNO INT NOT NULL IDENTITY(10,10),
	DNAME VARCHAR (50) NOT NULL,
	LOC VARCHAR (100) NOT NULL,
	CONSTRAINT PK_DEPT_DEPTNO PRIMARY KEY (DEPTNO));



CREATE TABLE EMP(
	EMPNO INT NOT NULL ,
	ENAME VARCHAR (50) NOT NULL,
	JOB VARCHAR (50) NOT NULL,
	MGR INT ,
	HIREDATE DATE NOT NULL,
	SAL INT NOT NULL,
	COMM INT ,
	DEPTNO INT NOT NULL,
	CONSTRAINT PK_EMP_EMPNO PRIMARY KEY (EMPNO),
	CONSTRAINT FK_EMP_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
	CONSTRAINT FK_EMP_MGR FOREIGN KEY (MGR) REFERENCES EMP (EMPNO)
	);

Create table PROJET(
numprojet int,
nom_de_projet VARCHAR (100) NOT NULL,
budget INT,
Constraint PK_PROJET_numprojet Primary key(numprojet)); 


